version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/examples/sample-app-java"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/examples/sample-app-node"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/examples/sample-app-python"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/examples/sample-app-java"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/examples/sample-app-node"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/examples/sample-app-python"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/dev"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/prod"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/stage"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ec2_observability"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ecs_observability"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/eks_observability"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/prometheus_backend"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
